In [5]:
import numpy as np

In [6]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
l=range(100)
%timeit [i**2 for i in l]

14.6 μs ± 314 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# create arrays

In [11]:
a=np.array([1,2,3,4,5])

In [12]:
print(a.ndim)

1


In [13]:
b=np.array([[1,2,3,4,],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
print(a.shape)

(5,)


In [25]:
print(b.shape)

(2, 2, 2)


In [24]:
print(c.shape)

(2, 2, 2)


# function of array

In [26]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
#using linspace
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [31]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [32]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [36]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [38]:
a=np.diag([4,3,2,1])
print(a)

[[4 0 0 0]
 [0 3 0 0]
 [0 0 2 0]
 [0 0 0 1]]


In [39]:
print(np.diag(a))

[4 3 2 1]


# Basic Data Types

In [40]:
a=np.arange(10)
print(a.dtype)

int64


In [41]:
a=np.arange(10,dtype="float64")
print(a.dtype)

float64


In [42]:
a=np.zeros((2,2))
print(a)
print(a.dtype)

[[0. 0.]
 [0. 0.]]
float64


# Other datatypes

In [43]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [44]:
a=np.array([True,False])
print(a.dtype)

bool


In [48]:
a=np.array(['Ajay','Karthik','Deeven k'])
print(a.dtype) #unicode string type

<U8


# Indexing and slicing

In [49]:
a=np.arange(10)
print(a[5])

5


In [55]:
a=np.diag([1,2,3])
print(a[2,1])

0


In [56]:
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


In [57]:
a[1,2]=4
print(a)

[[1 0 0]
 [0 2 4]
 [0 5 3]]


In [58]:
a[2,0]=2
print(a)

[[1 0 0]
 [0 2 4]
 [2 5 3]]


# Slicing

In [59]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [60]:
print(a[1:8:2])

[1 3 5 7]


In [61]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

# Copies and viewing

In [62]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [63]:
print(np.shares_memory(a,b))

True


In [64]:
b[0]=10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


# Random Number Generator

In [66]:
a=np.random.randint(0,20,15)
print(a)

[15  8 12 13  4 18  1  2  6  0 18 16 15  0  9]


In [68]:
mask=(a%2==0)

In [69]:
mask_a = a[mask]
print(mask_a)

[ 8 12  4 18  2  6  0 18 16  0]


In [70]:
a[mask] = -1
print(a)

[15 -1 -1 13 -1 -1  1 -1 -1 -1 -1 -1 15 -1  9]
