# Basic Operations

In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [5]:
a=np.array([1,2,3,4])
print(a-2)

[-1  0  1  2]


In [7]:
print(a**2)

[ 1  4  9 16]


# All arthematic operations

In [8]:
b=np.ones(4)+1
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [2. 2. 2. 2.]


In [9]:
print(a*b)

[2. 4. 6. 8.]


In [10]:
print(a+b)

[3. 4. 5. 6.]


In [11]:
c=np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [12]:
print(c*c)
print("******************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
******************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


# Comparision Operators

In [14]:
a=np.array([1,2,3,4])
b=np.array([5,2,3,4])
print(a==b)

[False  True  True  True]


In [16]:
print(a>b)

[False False False False]


In [17]:
a=np.array([1,2,3,4])
b=np.array([5,2,3,4])
c=np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [18]:
print(np.array_equal(a,c))

True


# Logical operators

In [25]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,1,0,0],dtype="bool")

In [26]:
print(np.logical_or(a,b))

[ True  True  True False]


In [27]:
print(np.logical_and(a,b))

[ True False False False]


# Trigonometry/Transcendental Fnuctions

In [28]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [29]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [32]:
print(np.cos(a))

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [33]:
print(np.tan(a))

[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128]


In [35]:
print(np.exp(a))

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


In [31]:
np.log(a)

C:\Users\kk397_ymf0gi0\AppData\Local\Temp\ipykernel_1192\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

# Basic Reductions

In [36]:
x=np.array([1,2,3,4])
print(np.sum(x))

10


In [37]:
x=np.array([[1,2],[1,2]])
print(x)

[[1 2]
 [1 2]]


In [38]:
x.sum(axis=0)

array([2, 4])

In [39]:
x.sum(axis=1)

array([3, 3])